language: node_js
node_js:
  - "stable"
addons:
  firefox: latest
  chrome: "stable"
branches:
  only:
    - master
jobs:
  include:
    - stage: test
      before_script:
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
        - sleep 3
      script: npm test
    - stage: npm release
      script: npm run build
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true