language: node_js
node_js:
  - "stable"
cache: npm
addons:
  #firefox: latest
  chrome: "stable"
# branches:
#   only:
#     - master
if: tag IS present
jobs:
  include:
    - stage: test with Karma
      # before_script:
      #   - export DISPLAY=:99.0
      #   - sh -e /etc/init.d/xvfb start
      #   - sleep 3
      script:
        - npm test
        - npm run lcov
    - stage: release to npm
      script: npm run build
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true