language: node_js
node_js:
  - "stable"
cache: npm
addons:
  chrome: "stable"
if: tag IS present
jobs:
  include:
    - stage: test with Karma
      script:
        - npm test
        - npm run lcov
    - stage: release to npm
      script: npm run build
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true